import Head from "next/head";
import Header from "@components/header";
import Navigation from "@components/navigation"


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <Navigation />
        <Header />
      </main>
    </>
  );
}
